# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: jenkins
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
        resources:
          limits:
            cpu: 800m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 300Mi
        livenessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: efs-claim
          mountPath: /var/jenkins_home
      volumes:
      - name: efs-claim
        persistentVolumeClaim:
           claimName: efs-claim
      

---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins
spec:
  type: ClusterIP
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
    - name: jnlpport
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-webops
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - test-stage.webops6-test.info
    secretName: test-tls-prod
  rules:
  - host: test-stage.webops6-test.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080