# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: jenkins
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   httpGet:
        #     scheme: HTTP
        #     path: /login
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        volumeMounts:
        - name: efs-claim
          mountPath: /var/jenkins_home
      volumes:
      - name: efs-claim
        persistentVolumeClaim:
           claimName: efs-claim
      

---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: jen-port
  selector:
    app: jenkins

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-webops
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - test-stage.webops6-test.info
    secretName: test-tls-prod
  rules:
  - host: test-stage.webops6-test.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080